name: "Question"
description: Ask a question.
title: "[QUESTION] - <title>"
labels: [
  "Not an issue"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Question"
      placeholder: A question...
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      description: By asking this question I made sure that ...
      options:
        - label: I am asking a sensible question.
          required: true
        - label: I am not trying to waste time.
          required: true
        - label: There is no (open or closed) issue related to my question.
          required: true



















